"""
api/server.py — FastAPI REST + WebSocket API for the Janus Brain.

Endpoints
---------
POST   /think              — synchronous single-turn input → response
WS     /think/stream       — LangGraph streaming: one JSON chunk per node
GET    /memory/search?q=…  — LTM semantic search
DELETE /memory/session     — flush STM (Redis) for the current session

OpenAPI docs are auto-generated by FastAPI at /docs and /redoc.

Dependency injection
--------------------
Three dependency functions (``get_brain_graph``, ``get_ltm_searcher``,
``get_stm_clearer``) are exposed at module level so tests can override them
via ``app.dependency_overrides[fn] = lambda: mock`` without touching live
services.
"""

from __future__ import annotations

import logging
from contextlib import asynccontextmanager
import time
from collections import defaultdict
from collections.abc import Callable
from threading import Lock
from typing import Any

from fastapi import Depends, FastAPI, HTTPException, Query, Request, WebSocket, WebSocketDisconnect
from pydantic import BaseModel, Field

from config import CONSOLIDATION_INTERVAL_SECONDS, RATE_LIMIT_MAX_CALLS, RATE_LIMIT_WINDOW_SECONDS
from models.brain_state import default_brain_state

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Rate limiter
# ---------------------------------------------------------------------------

class _RateLimiter:
    """Thread-safe sliding-window rate limiter keyed by client IP."""

    def __init__(self, max_calls: int, window_seconds: int) -> None:
        self.max_calls = max_calls
        self.window_seconds = window_seconds
        self._calls: dict[str, list[float]] = defaultdict(list)
        self._lock = Lock()

    def is_allowed(self, key: str) -> bool:
        now = time.time()
        with self._lock:
            cutoff = now - self.window_seconds
            self._calls[key] = [t for t in self._calls[key] if t > cutoff]
            if len(self._calls[key]) >= self.max_calls:
                return False
            self._calls[key].append(now)
            return True

    def reset(self) -> None:
        with self._lock:
            self._calls.clear()


# ---------------------------------------------------------------------------
# Application
# ---------------------------------------------------------------------------

@asynccontextmanager
async def _lifespan(app: FastAPI):  # type: ignore[type-arg]
    """Start the memory-consolidation scheduler on startup; stop it on shutdown."""
    from memory.consolidator import start_scheduler

    scheduler = start_scheduler(interval_seconds=CONSOLIDATION_INTERVAL_SECONDS)
    try:
        yield
    finally:
        scheduler.shutdown(wait=False)


app = FastAPI(
    title="Janus Process",
    description="Brain-inspired multi-agent system — REST + WebSocket API",
    version="0.1.0",
    lifespan=_lifespan,
)

# Attach the rate limiter to app state (overridable in tests via app.state.rate_limiter)
app.state.rate_limiter = _RateLimiter(
    max_calls=RATE_LIMIT_MAX_CALLS,
    window_seconds=RATE_LIMIT_WINDOW_SECONDS,
)


# ---------------------------------------------------------------------------
# Pydantic schemas
# ---------------------------------------------------------------------------

class ThinkRequest(BaseModel):
    input: str = Field(min_length=1, description="User input text (must not be empty)")


class ThinkResponse(BaseModel):
    response: str


class SearchResult(BaseModel):
    content: str
    metadata: dict[str, Any]


class SessionDeleteResponse(BaseModel):
    status: str


# ---------------------------------------------------------------------------
# Dependencies (overridable for testing)
# ---------------------------------------------------------------------------

_brain_graph = None  # module-level singleton


def get_brain_graph():
    """Return the compiled LangGraph brain (singleton, built on first call)."""
    global _brain_graph
    if _brain_graph is None:
        from agents.thalamus import build_graph
        _brain_graph = build_graph()
    return _brain_graph


def get_ltm_searcher() -> Callable:
    """Return the LTM search function."""
    from memory.long_term import search_ltm_with_metadata
    return search_ltm_with_metadata


def get_stm_clearer() -> Callable:
    """Return the STM clear function."""
    from memory.short_term import clear_short_term
    return clear_short_term


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.post("/think", response_model=ThinkResponse)
def think(
    http_request: Request,
    request: ThinkRequest,
    graph=Depends(get_brain_graph),
) -> ThinkResponse:
    """Run the full brain graph on *input* and return the final response.

    The input must be a non-empty string.  An empty string returns HTTP 422.
    Rate-limited to ``RATE_LIMIT_MAX_CALLS`` calls per ``RATE_LIMIT_WINDOW_SECONDS`` seconds.
    """
    client_ip = http_request.client.host if http_request.client else "unknown"
    if not http_request.app.state.rate_limiter.is_allowed(client_ip):
        raise HTTPException(status_code=429, detail="Rate limit exceeded — try again later")
    state = default_brain_state(request.input)
    result = graph.invoke(state)
    return ThinkResponse(response=result.get("final_response") or "")


@app.get("/memory/search", response_model=list[SearchResult])
def memory_search(
    q: str = Query(..., description="Search query — must not be empty"),
    k: int = Query(default=5, ge=1, le=50, description="Number of results"),
    collection: str = Query(default="episodic", description="ChromaDB collection"),
    searcher: Callable = Depends(get_ltm_searcher),
) -> list[SearchResult]:
    """Search long-term memory for documents semantically similar to *q*.

    Returns HTTP 400 when *q* is blank (e.g. ``?q=``).
    """
    if not q.strip():
        raise HTTPException(status_code=400, detail="Query 'q' must not be empty")
    results: list[dict[str, Any]] = searcher(q, collection, k, "mmr")
    return [SearchResult(content=r["content"], metadata=r["metadata"]) for r in results]


@app.delete("/memory/session", response_model=SessionDeleteResponse)
def delete_session(
    clearer: Callable = Depends(get_stm_clearer),
) -> SessionDeleteResponse:
    """Flush the short-term memory (Redis) for the current session.

    Returns HTTP 503 when the Redis service is unavailable.
    """
    try:
        clearer()
    except ConnectionError as exc:
        raise HTTPException(status_code=503, detail=str(exc))
    return SessionDeleteResponse(status="ok")


@app.websocket("/think/stream")
async def think_stream(
    websocket: WebSocket,
    graph=Depends(get_brain_graph),
) -> None:
    """Stream the brain's processing over WebSocket.

    Protocol
    --------
    Client → server:  ``{"input": "<text>"}``
    Server → client:  one ``{"type": "update", "node": "<name>", ...}`` per
                      LangGraph node, then ``{"type": "done"}`` on completion,
                      or ``{"type": "error", "detail": "..."}`` on failure.
    """
    await websocket.accept()
    try:
        data = await websocket.receive_json()
        input_text = (data.get("input") or "").strip()
        if not input_text:
            await websocket.send_json(
                {"type": "error", "detail": "Input must not be empty"}
            )
            await websocket.close(code=1008)
            return

        state = default_brain_state(input_text)
        # graph.stream() yields {"node_name": {state_fields}} after each node.
        for chunk in graph.stream(state):
            node_name = next(iter(chunk))
            node_state = chunk[node_name]
            payload: dict[str, Any] = {"type": "update", "node": node_name}
            if node_state.get("final_response"):
                payload["response"] = node_state["final_response"]
            await websocket.send_json(payload)

        await websocket.send_json({"type": "done"})
        await websocket.close()

    except WebSocketDisconnect:
        pass
    except Exception as exc:
        logger.exception("WebSocket /think/stream error: %s", exc)
        try:
            await websocket.send_json({"type": "error", "detail": str(exc)})
            await websocket.close(code=1011)
        except Exception:
            pass
